# permissions for end users to edit heliosconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helios-lb
    app.kubernetes.io/managed-by: kustomize
  name: heliosconfig-editor-role
rules:
- apiGroups:
  - balancer.helios.dev
  resources:
  - heliosconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - balancer.helios.dev
  resources:
  - heliosconfigs/status
  verbs:
  - get
