apiVersion: balancer.helios.dev/v1
kind: HeliosConfig
metadata:
  name: heliosconfig-sample-port
spec:
  # IMPORTANT: Replace with an unused IP in your network (use 'make find-free-ip')
  ipRange: "<YOUR_FREE_IP>"
  method: RoundRobin #  Optional: Load balancing method (defaults to RoundRobin) Enable Value: RoundRobin, LeastConnection, WeightedRoundRobin, IPHash, RandomSelection
  ports:
    - port: 80
    - port: 443
