apiVersion: v2
name: helios-lb
description: A Helm chart for Helios Load Balancer Controller
type: application
version: 0.1.0
appVersion: "v0.2.5"

# Dependencies and requirements
kubeVersion: ">=1.16.0-0"

# Keywords and categories for documentation
keywords:
  - kubernetes
  - loadbalancer
  - helios
  - networking
  - balancer

# Home page, sources, and documentation
home: https://github.com/somaz94/helios-lb
sources:
  - https://github.com/somaz94/helios-lb

# Maintainer information
maintainers:
  - name: somaz94
    url: https://github.com/somaz94

# Annotations for CRD handling
annotations:
  # This indicates that CRDs are required and should be created first
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-weight": "-5"

# Icon for the chart (optional)
icon: https://raw.githubusercontent.com/somaz94/helios-lb/main/docs/images/logo.png