apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helios-lb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helios-lb.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helios-lb.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "helios-lb.selectorLabels" . | nindent 8 }}
        control-plane: controller-manager
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helios-lb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        args:
        - --metrics-bind-address={{ .Values.controller.metrics.bindAddress | default ":8443" }}
        - --health-probe-bind-address={{ .Values.controller.health.bindAddress | default ":9082" }}
        {{- if .Values.controller.leaderElection.enabled }}
        - --leader-elect=true
        {{- end }}
        command:
        - /manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - ALL
          privileged: true
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path | default "/healthz" }}
            port: {{ .Values.probes.liveness.port | default 9082 }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 15 }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 20 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path | default "/readyz" }}
            port: {{ .Values.probes.readiness.port | default 9082 }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 5 }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
